(deftheme hh-tao-yin
  "Created 2018-07-22.")

(custom-theme-set-variables
 'hh-tao-yin
 '(ansi-color-names-vector ["#252525" "#DADADA" "#C3C3C3" "#F6F6F6" "#E8E8E8" "#DADADA" "#F1F1F1" "#F6F6F6"]))

(custom-theme-set-faces
 'hh-tao-yin
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F6F6F6" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#E8E8E8" :underline t :weight normal))))
 '(variable-pitch ((t (:foreground "#C3C3C3" :background "#171717"))))
 '(cursor ((t (:foreground "#F6F6F6" :background "#FAFAFA"))))
 '(escape-glyph ((t (:foreground "#F6F6F6" :bold t))))
 '(header-line ((t (:inherit mode-line))))
 '(fringe ((t (:background "#0E0E0E" :foreground "#FAFAFA" :weight bold))))
 '(highlight ((t (:background "#171717"))))
 '(success ((t (:foreground "#C3C3C3" :weight bold))))
 '(warning ((t (:foreground "#E8E8E8" :weight bold))))
 '(error ((t (:foreground "#FAFAFA" :weight bold))))
 '(compilation-info ((t (:foreground "#F6F6F6" :underline t))))
 '(compilation-line-number ((t (:foreground "#F6F6F6"))))
 '(compilation-mode-line-exit ((t (:foreground "#E8E8E8" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#DADADA" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F6F6F6" :weight bold))))
 '(match ((t (:background "#0E0E0E" :foreground "#E8E8E8" :weight bold))))
 '(isearch ((t (:foreground "#E8E8E8" :weight bold :background "#3C3C3C"))))
 '(isearch-fail ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(lazy-highlight ((t (:foreground "#E8E8E8" :weight bold :background "#252525"))))
 '(menu ((t (:foreground "#F6F6F6" :background "#171717"))))
 '(minibuffer-prompt ((t (:foreground "#050505" :background "#C3C3C3"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#F1F1F1" :background "#050505" :box nil :height 1.0))))
 '(mode-line-inactive ((t (:foreground "#C3C3C3" :background "#3C3C3C" :box nil :height 1.0))))
 '(mode-line-buffer-id ((t (:foreground "#FAFAFA" :weight bold))))
 '(region ((((class color) (min-colors 89)) (:background "#C3C3C3" :foreground "#0E0E0E")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#171717"))))
 '(trailing-whitespace ((t (:background "#DADADA"))))
 '(vertical-border ((t (:foreground "#616161" :background "#171717"))))
 '(font-lock-builtin-face ((t (:foreground "#F6F6F6" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#C3C3C3"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#9E9E9E"))))
 '(font-lock-constant-face ((t (:foreground "#F6F6F6" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "#C3C3C3" :weight bold :italic t))))
 '(font-lock-function-name-face ((t (:foreground "#F1F1F1"))))
 '(font-lock-keyword-face ((t (:foreground "#F6F6F6" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F6F6F6" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#E8E8E8"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F6F6F6" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#C3C3C3" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#C3C3C3" :slant oblique))))
 '(font-lock-type-face ((t (:foreground "#DADADA" :underline t))))
 '(font-lock-variable-name-face ((t (:foreground "#FAFAFA"))))
 '(font-lock-warning-face ((t (:foreground "#E8E8E8" :weight bold))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(anzu-mode-line ((t (:foreground "#F1F1F1" :weight bold))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#F6F6F6" :background nil)) (t (:foreground "#9E9E9E" :background nil))))
 '(diff-changed ((t (:foreground "#F6F6F6"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#DADADA" :background nil)) (t (:foreground "#9E9E9E" :background nil))))
 '(diff-refine-added ((t :inherit diff-added :weight bold)))
 '(diff-refine-removed ((t :inherit diff-removed :weight bold)))
 '(diff-header ((((class color) (min-colors 89)) (:background "#616161")) (t (:background "#F6F6F6" :foreground "#252525"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#616161" :foreground "#F6F6F6" :bold t)) (t (:background "#F6F6F6" :foreground "#252525" :bold t))))
 '(dired-directory ((t (:foreground "#C3C3C3" :bold t))))
 '(ediff-current-diff-A ((t (:background "#3C3C3C"))))
 '(ediff-current-diff-Ancestor ((t (:background "#3C3C3C"))))
 '(ediff-current-diff-B ((t (:background "#3C3C3C"))))
 '(ediff-current-diff-C ((t (:background "#3C3C3C"))))
 '(ediff-even-diff-A ((t (:background "#252525"))))
 '(ediff-even-diff-Ancestor ((t (:background "#252525"))))
 '(ediff-even-diff-B ((t (:background "#252525"))))
 '(ediff-even-diff-C ((t (:background "#252525"))))
 '(ediff-odd-diff-A ((t (:background "#252525"))))
 '(ediff-odd-diff-Ancestor ((t (:background "#252525"))))
 '(ediff-odd-diff-B ((t (:background "#252525"))))
 '(ediff-odd-diff-C ((t (:background "#252525"))))
 '(ediff-fine-diff-A ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(ediff-fine-diff-Ancestor ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(ediff-fine-diff-B ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(ediff-fine-diff-C ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(flx-highlight-face ((t (:foreground "#E8E8E8" :weight bold))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#DADADA") :inherit unspecified)) (t (:foreground "#616161" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#C3C3C3") :inherit unspecified)) (t (:foreground "#C3C3C3" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave))) (:underline (:style wave :color "#9E9E9E") :inherit unspecified)) (t (:foreground "#DADADA" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:inherit error))))
 '(flycheck-fringe-warning ((t (:inherit fringe))))
 '(flycheck-fringe-info ((t (:inherit fringe))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#E8E8E8") :inherit unspecified)) (t (:foreground "#E8E8E8" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#DADADA") :inherit unspecified)) (t (:foreground "#C3C3C3" :weight bold :underline t))))
 '(gnus-group-mail-1 ((t (:bold t :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((t (:bold t :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((t (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((t (:bold t :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((t (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((t (:bold t :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((t (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((t (:bold t :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((t (:bold t :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((t (:bold t :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((t (:bold t :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((t (:bold t :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((t (:bold t :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((t (:bold t :inherit gnus-group-news-low-empty))))
 '(gnus-header-content ((t (:inherit message-header-other))))
 '(gnus-header-from ((t (:inherit message-header-from))))
 '(gnus-header-name ((t (:inherit message-header-name))))
 '(gnus-header-newsgroups ((t (:inherit message-header-other))))
 '(gnus-header-subject ((t (:inherit message-header-subject))))
 '(gnus-summary-cancelled ((t (:foreground "#E8E8E8"))))
 '(gnus-summary-high-ancient ((t (:foreground "#E8E8E8"))))
 '(gnus-summary-high-read ((t (:foreground "#C3C3C3" :weight bold))))
 '(gnus-summary-high-ticked ((t (:foreground "#E8E8E8" :weight bold))))
 '(gnus-summary-high-unread ((t (:foreground "#F6F6F6" :weight bold))))
 '(gnus-summary-low-ancient ((t (:foreground "#E8E8E8"))))
 '(gnus-summary-low-read ((t (:foreground "#C3C3C3"))))
 '(gnus-summary-low-ticked ((t (:foreground "#E8E8E8" :weight bold))))
 '(gnus-summary-low-unread ((t (:foreground "#F6F6F6"))))
 '(gnus-summary-normal-ancient ((t (:foreground "#E8E8E8"))))
 '(gnus-summary-normal-read ((t (:foreground "#C3C3C3"))))
 '(gnus-summary-normal-ticked ((t (:foreground "#E8E8E8" :weight bold))))
 '(gnus-summary-normal-unread ((t (:foreground "#F6F6F6"))))
 '(gnus-summary-selected ((t (:foreground "#F6F6F6" :weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "#F6F6F6"))))
 '(gnus-group-news-2-empty ((t (:foreground "#F1F1F1"))))
 '(gnus-group-news-3-empty ((t (:foreground "#DADADA"))))
 '(gnus-group-news-4-empty ((t (:foreground "#C3C3C3"))))
 '(gnus-group-news-5-empty ((t (:foreground "#9E9E9E"))))
 '(gnus-group-news-6-empty ((t (:foreground "#616161"))))
 '(gnus-group-news-low-empty ((t (:foreground "#616161"))))
 '(gnus-signature ((t (:foreground "#F6F6F6"))))
 '(helm-header ((t (:foreground "#C3C3C3" :background "#171717" :underline nil :box nil))))
 '(helm-source-header ((t (:foreground "#F6F6F6" :background "#0E0E0E" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
 '(helm-selection ((t (:background "#3C3C3C" :underline nil))))
 '(helm-selection-line ((t (:background "#3C3C3C"))))
 '(helm-visible-mark ((t (:foreground "#252525" :background "#E8E8E8"))))
 '(helm-candidate-number ((t (:foreground "#F6F6F6" :background "#0E0E0E"))))
 '(helm-separator ((t (:foreground "#DADADA" :background "#171717"))))
 '(helm-bookmark-addressbook ((t (:foreground "#E8E8E8" :background "#171717"))))
 '(helm-bookmark-directory ((t (:foreground nil :background nil :inherit helm-ff-directory))))
 '(helm-bookmark-file ((t (:foreground nil :background nil :inherit helm-ff-file))))
 '(helm-bookmark-gnus ((t (:foreground "#DADADA" :background "#171717"))))
 '(helm-bookmark-info ((t (:foreground "#E8E8E8" :background "#171717"))))
 '(helm-bookmark-man ((t (:foreground "#F6F6F6" :background "#171717"))))
 '(helm-bookmark-w3m ((t (:foreground "#DADADA" :background "#171717"))))
 '(helm-buffer-not-saved ((t (:foreground "#DADADA" :background "#171717"))))
 '(helm-buffer-process ((t (:foreground "#F1F1F1" :background "#171717"))))
 '(helm-buffer-saved-out ((t (:foreground "#F6F6F6" :background "#171717"))))
 '(helm-buffer-size ((t (:foreground "#616161" :background "#171717"))))
 '(helm-buffer-directory ((t (:foreground "#DADADA" :background "#171717"))))
 '(helm-locate-finish ((t (:foreground "#9E9E9E" :background "#171717"))))
 '(helm-ff-dotted-symlink-directory ((t (:foreground "#616161" :background "#252525"))))
 '(helm-ff-directory ((t (:foreground "#F1F1F1" :background "#171717" :weight bold))))
 '(helm-ff-file ((t (:foreground "#F6F6F6" :background "#171717" :weight normal))))
 '(helm-ff-executable ((t (:foreground "#E8E8E8" :background "#171717" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#DADADA" :background "#171717" :weight bold))))
 '(helm-ff-symlink ((t (:foreground "#F6F6F6" :background "#171717" :weight bold))))
 '(helm-ff-prefix ((t (:foreground "#252525" :background "#F6F6F6" :weight normal))))
 '(helm-grep-cmd-line ((t (:foreground "#F1F1F1" :background "#171717"))))
 '(helm-grep-file ((t (:foreground "#F6F6F6" :background "#171717"))))
 '(helm-grep-finish ((t (:foreground "#E8E8E8" :background "#171717"))))
 '(helm-grep-lineno ((t (:foreground "#616161" :background "#171717"))))
 '(helm-match ((t (:foreground "#F1F1F1" :background "#252525"))))
 '(helm-grep-match ((t (:inherit helm-match))))
 '(helm-moccur-buffer ((t (:foreground "#F1F1F1" :background "#171717"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#404b5e")) (t :weight bold)))
 '(ido-first-match ((t (:foreground "#F6F6F6" :weight bold))))
 '(ido-only-match ((t (:foreground "#E8E8E8" :weight bold))))
 '(ido-subdir ((t (:foreground "#F6F6F6"))))
 '(ido-indicator ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(js2-warning ((t (:underline "#0E0E0E"))))
 '(js2-error ((t (:foreground "#DADADA" :weight bold))))
 '(js2-jsdoc-tag ((t (:foreground "#9E9E9E"))))
 '(js2-jsdoc-type ((t (:foreground "#E8E8E8"))))
 '(js2-jsdoc-value ((t (:foreground "#F1F1F1"))))
 '(js2-jsdoc-html-tag-name ((t (:foreground "#E8E8E8"))))
 '(js2-jsdoc-html-tag-delimiter ((t (:foreground "#F1F1F1"))))
 '(js2-function-param ((t (:foreground "#F1F1F1"))))
 '(js2-function-call ((t (:foreground "#F1F1F1" :underline t))))
 '(js2-object-property ((t (:foreground "#F1F1F1" :slant italic))))
 '(js2-external-variable ((t (:foreground "#DADADA" :italic t))))
 '(linum ((t (:foreground "#E8E8E8" :background "#171717"))))
 '(magit-section-highlight ((t (:foreground "#E8E8E8" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#F6F6F6" :weight bold))))
 '(magit-section-heading ((t (:foreground "#F6F6F6" :weight bold))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-name ((t (:foreground "#DADADA"))))
 '(message-header-other ((t (:foreground "#C3C3C3"))))
 '(message-header-to ((t (:foreground "#F6F6F6" :weight bold))))
 '(message-header-cc ((t (:foreground "#F6F6F6" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#F6F6F6" :weight bold))))
 '(message-header-subject ((t (:foreground "#E8E8E8" :weight bold))))
 '(message-header-xheader ((t (:foreground "#C3C3C3"))))
 '(message-mml ((t (:foreground "#F6F6F6" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment-face))))
 '(mu4e-cited-1-face ((t (:foreground "#E8E8E8" :slant italic))))
 '(mu4e-cited-2-face ((t (:foreground "#E8E8E8" :slant italic))))
 '(mu4e-cited-3-face ((t (:foreground "#C3C3C3" :slant italic))))
 '(mu4e-cited-4-face ((t (:foreground "#C3C3C3" :slant italic))))
 '(mu4e-cited-5-face ((t (:foreground "#616161" :slant italic))))
 '(mu4e-cited-6-face ((t (:foreground "#9E9E9E" :slant italic))))
 '(mu4e-cited-7-face ((t (:foreground "#E8E8E8" :slant italic))))
 '(mu4e-replied-face ((t (:foreground "#9E9E9E"))))
 '(mu4e-trashed-face ((t (:foreground "#9E9E9E" :strike-through t))))
 '(org-agenda-date-today ((t (:foreground "#FAFAFA" :slant italic :weight bold))))
 '(org-agenda-clocking ((t (:foreground "#FAFAFA" :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#F6F6F6" :weight bold))))
 '(org-checkbox ((t (:foreground "#FAFAFA" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#E8E8E8" :underline t))))
 '(org-formula ((t (:foreground "#E8E8E8"))))
 '(org-macro ((t (:foreground "#E8E8E8" :italic t))))
 '(org-headline-done ((t (:foreground "#F1F1F1"))))
 '(org-hide ((t (:foreground "#0E0E0E"))))
 '(org-document-title ((t (:foreground "#F1F1F1" :height 1.0 :bold t))))
 '(org-document-info ((t (:foreground "#616161" :height 1.0))))
 '(org-document-info-keyword ((t (:foreground "#616161" :height 1.0))))
 '(org-level-1 ((t (:foreground "#FAFAFA" :height 1.0 :bold t))))
 '(org-level-2 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-level-3 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-level-4 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-level-5 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-level-6 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-level-7 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-level-8 ((t (:foreground "#FAFAFA" :height 1.0 :bold nil))))
 '(org-link ((t (:foreground "#E8E8E8" :underline t))))
 '(org-scheduled ((t (:foreground "#F6F6F6"))))
 '(org-scheduled-previously ((t (:foreground "#DADADA"))))
 '(org-scheduled-today ((t (:foreground "#E8E8E8"))))
 '(org-sexp-date ((t (:foreground "#E8E8E8" :underline t))))
 '(org-table ((t (:foreground "#E8E8E8"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-time-grid ((t (:foreground "#E8E8E8"))))
 '(org-done ((t (:bold t :background "#252525" :foreground "#F6F6F6" :weight bold))))
 '(org-todo ((t (:bold t :background "#252525" :foreground "#9E9E9E" :weight bold))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:bold t :foreground "#DADADA" :weight bold :underline nil))))
 '(org-column ((t (:background "#0E0E0E"))))
 '(org-column-title ((t (:background "#0E0E0E" :underline t :weight bold))))
 '(org-mode-line-clock ((t (:foreground "#F6F6F6" :background "#0E0E0E"))))
 '(org-mode-line-clock-overrun ((t (:foreground "#252525" :background "#C3C3C3"))))
 '(org-checkbox-statistics-todo ((t (:foreground "#090909" :background "#F1F1F1" :bold t))))
 '(org-ellipsis ((t (:foreground "#9E9E9E"))))
 '(org-footnote ((t (:foreground "#F1F1F1"))))
 '(org-meta-line ((t (:foreground "#9E9E9E" :height 1.0))))
 '(org-special-keyword ((t (:inherit org-meta-line))))
 '(org-property-value ((t (:foreground "#C3C3C3" :height 1.0))))
 '(org-block ((t (:background "#252525" :foreground "#C3C3C3" :height 1.0))))
 '(outline-1 ((t (:foreground "#E8E8E8"))))
 '(outline-2 ((t (:foreground "#F6F6F6"))))
 '(outline-3 ((t (:foreground "#DADADA"))))
 '(outline-4 ((t (:foreground "#E8E8E8"))))
 '(outline-5 ((t (:foreground "#F1F1F1"))))
 '(outline-6 ((t (:foreground "#E8E8E8"))))
 '(outline-7 ((t (:foreground "#616161"))))
 '(outline-8 ((t (:foreground "#616161"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#616161"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#9E9E9E"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#C3C3C3"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#DADADA"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#E8E8E8"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#F1F1F1"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#F6F6F6"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#FAFAFA"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#FAFAFA"))))
 '(sh-heredoc ((t (:foreground "#F6F6F6" :bold t))))
 '(sh-quoted-exec ((t (:foreground "#DADADA"))))
 '(show-paren-mismatch ((t (:foreground "#050505" :background "#616161" :weight bold))))
 '(show-paren-match ((t (:foreground "#E8E8E8" :background "#0E0E0E" :weight bold))))
 '(sp-show-pair-mismatch-face ((t (:foreground "#FAFAFA" :background "#0E0E0E"))))
 '(sp-show-pair-match-face ((t (:foreground "#FAFAFA" :background "#3C3C3C" :underline nil))))
 '(speedbar-button-face ((t (:foreground "#E8E8E8"))))
 '(speedbar-directory-face ((t (:foreground "#F1F1F1"))))
 '(speedbar-file-face ((t (:foreground "#F6F6F6"))))
 '(speedbar-highlight-face ((t (:foreground "#252525" :background "#E8E8E8"))))
 '(speedbar-selected-face ((t (:foreground "#DADADA"))))
 '(speedbar-separator-face ((t (:foreground "#252525" :background "#DADADA"))))
 '(speedbar-tag-face ((t (:foreground "#F6F6F6"))))
 '(term-color-black ((t (:foreground "#252525" :background "#0E0E0E"))))
 '(term-color-red ((t (:foreground "#C3C3C3" :background "#616161"))))
 '(term-color-green ((t (:foreground "#C3C3C3" :background "#E8E8E8"))))
 '(term-color-yellow ((t (:foreground "#E8E8E8" :background "#F6F6F6"))))
 '(term-color-blue ((t (:foreground "#DADADA" :background "#616161"))))
 '(term-color-magenta ((t (:foreground "#DADADA" :background "#DADADA"))))
 '(term-color-cyan ((t (:foreground "#F1F1F1" :background "#E8E8E8"))))
 '(term-color-white ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "#FAFAFA" :weight bold))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#C3C3C3" :weight bold))))
 '(undo-tree-visualizer-default-face ((t (:foreground "#F6F6F6"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#F6F6F6"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#F1F1F1"))))
 '(vhl/default-face ((t (:background "#171717"))))
 '(whitespace-space ((t (:background "#3C3C3C" :foreground "#3C3C3C"))))
 '(whitespace-hspace ((t (:background "#3C3C3C" :foreground "#3C3C3C"))))
 '(whitespace-tab ((t (:background "#C3C3C3"))))
 '(whitespace-newline ((t (:foreground "#3C3C3C"))))
 '(whitespace-trailing ((t (:background "#DADADA"))))
 '(whitespace-line ((t (:background "#171717" :foreground "#DADADA"))))
 '(whitespace-space-before-tab ((t (:background "#E8E8E8" :foreground "#E8E8E8"))))
 '(whitespace-indentation ((t (:background "#F6F6F6" :foreground "#DADADA"))))
 '(whitespace-empty ((t (:background "#F6F6F6"))))
 '(whitespace-space-after-tab ((t (:background "#F6F6F6" :foreground "#DADADA"))))
 '(which-func ((t (:foreground "#090909"))))
 '(company-echo-common ((t (:foreground "#F6F6F6"))))
 '(company-preview ((t (:background "#3C3C3C" :foreground "#E8E8E8"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "#F6F6F6" :weight bold))))
 '(company-scrollbar-fg ((t (:background "#616161"))))
 '(company-tooltip ((t (:background "#252525" :foreground "#E8E8E8"))))
 '(company-tooltip-annotation ((t (:inherit company-tooltip :foreground "#C3C3C3"))))
 '(company-tooltip-annotation-selection ((t (:inherit company-tooltip-selection :foreground "#C3C3C3"))))
 '(company-tooltip-common ((t (:inherit company-tooltip :foreground "#E8E8E8"))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :foreground "#F6F6F6"))))
 '(company-tooltip-selection ((t (:inherit company-tooltip :background "#616161" :foreground "#050505"))))
 '(company-scrollbar-bg ((t (:inherit company-tooltip))))
 '(company-tooltip-mouse ((t (:inherit company-tooltip-selection))))
 '(neo-dir-link-face ((t (:inherit diredp-dir-priv))))
 '(neo-expand-btn-face ((t (:foreground "#E8E8E8" :bold t))))
 '(neo-file-link-face ((t (:foreground "#C3C3C3"))))
 '(neo-root-dir-face ((t (:foreground "#9E9E9E" :background "#090909"))))
 '(compilation-error ((t (:foreground "#F1F1F1" :underline t :bold t))))
 '(avy-lead-face ((t (:background "#9E9E9E" :foreground "#050505" :bold t))))
 '(avy-lead-face-0 ((t (:background "#C3C3C3" :foreground "#050505" :bold t))))
 '(avy-lead-face-1 ((t (:background "#DADADA" :foreground "#050505" :bold t))))
 '(avy-lead-face-2 ((t (:background "#E8E8E8" :foreground "#050505" :bold t))))
 '(avy-background-face ((t (:background "#0E0E0E" :foreground "#616161" :bold t))))
 '(info-menu-star ((t (:foreground "#E8E8E8" :bold t))))
 '(custom-variable-tag ((t (:foreground "#E8E8E8" :bold t))))
 '(default ((t (:foreground "#DADADA" :background "#171717")))))

(provide-theme 'hh-tao-yin)
